version: '3.9'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - config_example.env
    depends_on:
      - neo4j
      - ollama
    volumes:
      - .:/app
    networks:
      - graphnet

  neo4j:
    image: neo4j:2025.03.0
    container_name: neo4j
    ports:
      - "7474:7474"  # Neo4j Browser
      - "7687:7687"  # Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/password123
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_server_memory_pagecache_size=512M
      - NEO4J_server_memory_heap_initial__size=1G
      - NEO4J_server_memory_heap_max__size=2G
      - NEO4J_PLUGINS=["graph-data-science", "apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*,gds.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_meta_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      
    volumes:
      - neo4j_data:/data
    networks:
      - graphnet

  ollama:
    build:
      context: .
      dockerfile: ollama.Dockerfile
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    networks:
      - graphnet

volumes:
  neo4j_data:
  ollama_models:

networks:
  graphnet:
    driver: bridge